# Generated by Django 3.2.24 on 2024-02-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.CharField(default='empty', help_text='List of ingredients (up to 500 characters)', max_length=500, verbose_name='Ingredients'),
        ),
    ]
