# Generated by Django 3.2.24 on 2024-02-17 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240216_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.PositiveSmallIntegerField(help_text='Size visible to the customer (gm.)', unique=True, verbose_name='size in grams')),
                ('price', models.PositiveSmallIntegerField(help_text='Price payable by customer (Rs.)', verbose_name='selling price (Rs.)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sku', to='products.product')),
            ],
            options={
                'verbose_name': 'Sku',
                'verbose_name_plural': 'Skus',
                'db_table': 'sku',
                'ordering': [],
            },
        ),
    ]
