# Generated by Django 3.2.24 on 2024-02-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240217_1454'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sku',
            unique_together={('product', 'price')},
        ),
    ]
