# Generated by Django 3.2.24 on 2024-02-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_sku_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='price',
            field=models.PositiveSmallIntegerField(help_text='Selling price payable by customer (Rs.)', verbose_name='Selling Price (Rs.)'),
        ),
        migrations.RenameField(
            model_name='sku',
            old_name='price',
            new_name='selling_price',
        ),
    ]
