# Generated by Django 3.2.24 on 2024-02-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_sku_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='cost_price',
            field=models.PositiveSmallIntegerField(blank=True, default=10, help_text='Cost Price', verbose_name='cost price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='platform_commission',
            field=models.PositiveSmallIntegerField(blank=True, default='1', help_text='Platform Commission', verbose_name='platform commission'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sku',
            name='selling_price',
            field=models.PositiveSmallIntegerField(help_text='Price payable by customer (Rs.)', verbose_name='selling price (Rs.)'),
        ),
    ]
