# Generated by Django 3.2.24 on 2024-02-18 07:32

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20240217_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='measurement_unit',
            field=models.CharField(choices=[('gm', 'Grams'), ('kg', 'Kilograms'), ('mL', 'Milliliters'), ('L', 'Liters'), ('pc', 'Piece')], default='gm', max_length=2),
        ),
        migrations.AddField(
            model_name='sku',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending for Approval (default)'), (2, 'Approved'), (3, 'Discontinued')], default=1),
        ),
        migrations.AlterField(
            model_name='sku',
            name='size',
            field=models.PositiveSmallIntegerField(help_text='Size visible to the customer (gm.)', validators=[products.models.validate_size], verbose_name='size in grams'),
        ),
    ]
